### PR TITLE
Update android support

### PR DESCRIPTION
**Pull request by riso**
- use AndroidX
- automatically inject required meta-data in parent AndroidManifest
- use latest GPay APIs
- support any supported GPay gateway
- return additional data from GPay (e.g. card info)

### CODE REVIEW

**Comment by narobertson42** [comment]
Looks good to me 👍

**Comment by konclave** [comment]
I've got some issues using `react-native-payments` with this PR merged. 
Trying to check if device supports Google Pay with calling `canMakePayments()`:
```
import {canMakePayments} from 'react-native-payments';

const paymentsParams = {
  supportedNetworks: ['visa', 'mastercard'],
  allowedPaymentMethods: ['CARD', 'TOKENIZED_CARD'],
  environment: 'TEST',
};

canMakePayments(paymentsParams)
  .then(...)
  .catch(...)
```

The execution fails with some error in native code: 
```
{ [TypeError: null is not an object (evaluating 'ReactNativePayments.canMakePayments')]
      line: 113556,
      column: 30,
      sourceURL: 'http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false' }
```

When I looked up a `canMakePayments` function argument type, saw there that `allowedPaymentsMethods` is an array on number. But I didn't catch up what numbers that should be. 

Could you please help me? What am I doing wrong?

**Comment by riso** [comment]
hey, those values are defined here https://developers.google.com/android/reference/com/google/android/gms/wallet/WalletConstants.html and they are the values for `PAYMENT_METHOD_CARD` and `PAYMENT_METHOD_TOKENIZED_CARD`.. or `[1, 2]`

**Comment by konclave** [comment]
Thank you! And finally i've figured out why there was an error on calling `canMakePayments`. Just forgot to add `ReactNativePaymentsPackage` to the packages list 🤦‍♂️.

**Pull request merged**
